### ISSUE TITLE
这项目能调整成maven格式吗

### ISSUE THREAD

**Issue by duansheli** [oliverwy/DhDesignpattern#1]
用idea打开的工程
![image](https://user-images.githubusercontent.com/8579595/86388441-62c7da80-bcc7-11ea-8abc-3b21b5299df2.png)
通常都有project视图

这项目用idea打开只有一个视图
![image](https://user-images.githubusercontent.com/8579595/86388542-8ee35b80-bcc7-11ea-93e3-da2de6cdc9aa.png)
![image](https://user-images.githubusercontent.com/8579595/86388590-a3275880-bcc7-11ea-90e5-418cf2b2fcf9.png)

另外文件 cc.ucls 是做什么用的 
应该用什么软件打开

**Comment by duansheli** [comment]
另外ch1simplefactory 可以改成 ch01_simplefactory

**Comment by oliverwy** [comment]
我使用Eclipse创建的这个工程。
请Eclipse安装ObjectAid UML打开cc.ucls文件
https://www.objectaid.com
我抽时间更新文件结构
